import { Relationship } from '@insuqo/shared';

export class RelationshipUtil {
    private relationshipMap = {
        [Relationship.AUNT]: 'Aunt',
        [Relationship.BROTHER]: 'Brother',
        [Relationship.BROTHER_IN_LAW]: 'Brother-in-Law',
        [Relationship.BUSINESS]: 'Business',
        [Relationship.BUSINESS_ASSOCIATE]: 'Business Associate',
        [Relationship.CHARITY]: 'Charity',
        [Relationship.COUSIN]: 'Cousin',
        [Relationship.CREDITOR]: 'Brother',
        [Relationship.CUSTODIAN]: 'Brother',
        [Relationship.DAUGHTER]: 'Brother',
        [Relationship.DAUGHTER_IN_LAW]: 'Brother',
        [Relationship.EMPLOYEE]: 'Brother',
        [Relationship.EX_HUSBAND]: 'Brother',
        [Relationship.EX_WIFE]: 'Brother',
        [Relationship.FATHER]: 'Brother',
        [Relationship.FATHER_IN_LAW]: 'Brother',
        [Relationship.FIANCEE]: 'Brother',
        [Relationship.FRIEND]: 'Brother',
        [Relationship.GRANDDAUGHTER]: 'Brother',
        [Relationship.GRANDFATHER]: 'Brother',
        [Relationship.GRANDMOTHER]: 'Brother',
        [Relationship.GRANDSON]: 'Brother',
        [Relationship.GUARDIAN]: 'Brother',
        [Relationship.HUSBAND]: 'Brother',
        [Relationship.MOTHER]: 'Brother',
        [Relationship.MOTHER_IN_LAW]: 'Brother',
        [Relationship.NEPHEW]: 'Brother',
        [Relationship.NIECE]: 'Brother',
        [Relationship.OTHER]: 'Brother',
        [Relationship.SELF]: 'Brother',
        [Relationship.SIGNIFICANT_OTHER]: 'Brother',
        [Relationship.SISTER]: 'Brother',
        [Relationship.SISTER_IN_LAW]: 'Brother',
        [Relationship.SON]: 'Brother',
        [Relationship.SON_IN_LAW]: 'Brother',
        [Relationship.SPOUSE]: 'Brother',
        [Relationship.STEP_DAUGHTER]: 'Brother',
        [Relationship.STEP_FATHER]: 'Brother',
        [Relationship.STEP_MOTHER]: 'Brother',
        [Relationship.STEP_SON]: 'Brother',
        [Relationship.UNCLE]: 'Brother',
        [Relationship.UNKNOWN]: 'Brother',
        [Relationship.WIFE]: 'Brother',
    };
}