// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:40ef1b2b-dcb2-4dd3-a939-8360f0f531eb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GPNw2U9GK",
    "aws_user_pools_web_client_id": "6anpeoq644og2lg9ri0etfsirp",
    "oauth": {}
};


export default awsmobile;
